import { StyleSheet } from 'react-native';

export const adminStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#FAF8F3' },
  centerContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: '#FAF8F3' },
  list: { padding: 16, paddingBottom: 100 },
  card: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderRadius: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#E8DCC8',
    overflow: 'hidden',
  },
  accentBar: {
    width: 4,
  },
  cardContent: {
    flex: 1,
    padding: 14,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#3A2F26',
    marginBottom: 4,
    fontFamily: 'Georgia',
  },
  cardSubtitle: {
    fontSize: 13,
    color: '#7A6A5A',
    marginBottom: 6,
    fontStyle: 'italic',
  },
  cardDescription: {
    fontSize: 13,
    color: '#7A6A5A',
    lineHeight: 18,
    marginBottom: 10,
  },
  cardHebrew: {
    fontSize: 16,
    color: '#2A2018',
    textAlign: 'right',
    lineHeight: 26,
    marginBottom: 8,
    fontFamily: 'Georgia',
  },
  cardEnglish: {
    fontSize: 14,
    color: '#5A4A3A',
    lineHeight: 20,
    marginBottom: 10,
    fontFamily: 'Georgia',
  },
  cardActions: {
    flexDirection: 'row',
    gap: 8,
  },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: '#FFF9F0',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#E8DCC8',
    gap: 4,
  },
  deleteButton: {
    backgroundColor: '#FFF1E6',
    borderColor: '#F4D4B8',
  },
  actionText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#8B4513',
  },
  deleteText: {
    color: '#D2691E',
  },
  fab: {
    position: 'absolute',
    bottom: 24,
    right: 24,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#8B4513',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 6,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modalContent: {
    backgroundColor: '#FAF8F3',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: '90%',
    minHeight: '60%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#E8DCC8',
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#3A2F26',
    fontFamily: 'Georgia',
  },
  modalScroll: {
    padding: 20,
    paddingBottom: 40,
  },
  label: {
    fontSize: 13,
    fontWeight: '600',
    color: '#5A4A3A',
    marginBottom: 6,
    marginTop: 12,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  input: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#E8DCC8',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
    color: '#3A2F26',
  },
  hebrewInput: {
    textAlign: 'right',
    fontFamily: 'Georgia',
    fontSize: 18,
    minHeight: 60,
  },
  textarea: {
    minHeight: 80,
    textAlignVertical: 'top',
  },
  colorGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  colorSwatch: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  colorSwatchActive: {
    borderColor: '#3A2F26',
  },
  saveButton: {
    backgroundColor: '#8B4513',
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 24,
  },
  saveButtonDisabled: { opacity: 0.6 },
  saveButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  picker: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  pickerOption: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#fff',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E8DCC8',
  },
  pickerOptionActive: {
    backgroundColor: '#8B4513',
    borderColor: '#8B4513',
  },
  pickerOptionText: {
    fontSize: 13,
    color: '#5A4A3A',
    fontWeight: '500',
  },
  pickerOptionTextActive: {
    color: '#fff',
  },
});
